language: rust
rust:
  - stable
  - nightly
node_js: 12

env:
  - NODE_ENV=ci
  - NODE_ENV=ci-staging
cache: yarn

before_script:
  - rustup target add wasm32-unknown-unknown

script:
  - yarn test
  - yarn lint
