matrix:
  include:
    language: node_js
    node_js: 12
  include:
    language: rust
    rust:
      - stable
      - nightly

env:
  - NODE_ENV=ci
  - NODE_ENV=ci-staging
cache: yarn
script:
  - rustup target add wasm32-unknown-unknown
  - yarn test
  - yarn lint
