language: node_js
node_js:
  - 12.0
env:
  - NODE_ENV=ci
  - NODE_ENV=ci-staging
cache: yarn
os:
  - linux
  - osx
  - windows
before_install:
  - curl https://sh.rustup.rs -sSf -m 60 | sh -s -- -y -v --default-toolchain stable
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then HOME="/c/Users/travis"; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - git config --global core.autocrlf false
  - rustup target add wasm32-unknown-unknown
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn test
  - yarn lint