language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows
env:
  - NODE_ENV=ci
  - NODE_ENV=ci-staging
cache: yarn

before_install:
  - rustup target add wasm32-unknown-unknown
  - nvm install 12
  - nvm use 12
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn test
  - yarn lint
