version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/templates/vanilla"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/templates/react"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/templates/vue"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/templates/angular"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/common/contracts/assemblyscript"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
  - package_manager: "rust:cargo"
    directory: "/common/contracts/rust"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
