name: Tests
on: push
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        contract: [assemblyscript, rust]
        frontend: ['vanilla', 'react', 'vue', 'angular']
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Install modules
      run: yarn
    - name: Run tests
      env:
        CONTRACT: ${{ matrix.contract }}
        FRONTEND: ${{ matrix.frontend }}
        NEAR_ENV: ci 
        IS_GITHUB_ACTION: true
      run: yarn test